image: Visual Studio 2019
install:
  - dotnet tool install -g Cake.Tool --version 0.35.0 
build_script:
- cmd: >-

    dotnet cake -Target=UpdateBuildVersion

    dotnet cake -Target=CreateArtifact -bootstrapVersion=3 -buildConfig=Release

    dotnet cake -Target=CreateArtifact -bootstrapVersion=4 -buildConfig=Release
    
test: off
cache:
  - 'tools -> build.cake'
